export const rooms = [
    
    {
        id: '1',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '2',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '3',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '4',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '5',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }

    },
    {
        id: '6',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '7',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '8',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '9',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '10',
        name: 'Studio',
        price: 149,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '11',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '12',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '13',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '14',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '15',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '16',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '17',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '18',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '19',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '20',
        name: 'Onebed',
        price: 99,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '21',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '22',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '23',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '24',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '25',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '26',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '27',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '28',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '29',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '30',
        name: 'Twobed',
        price: 154,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '31',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '32',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '33',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '34',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '35',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '36',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '37',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '38',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '39',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '40',
        name: 'Presidential',
        price: 259,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '41',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '42',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '43',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '44',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '45',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '46',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '47',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '48',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '49',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
    {
        id: '50',
        name: 'Premium',
        price: 324,
        available: true,
        guestInfo: {
            fullName: '',
            address: '',
            email: '',
            zipcode: '',
            state: '',
            phoneNumber: '',
        },
        payment: {
            cardCompany: '',
            cardNumber: '',
            csv: '',
            expirationDate: '',
            cardholderName: '',
        }
    },
]
